---
project_name: projector
builds:
  - main: .
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - arm
      - arm64
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0

archive:
  files:
    - LICENSE
    - README.md
    # - docs/man/*
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^goreleaser:'
      - '^Makefile'
