[package]
authors = ["Mathew Robinson <chasinglogic@gmail.com>"]
description = "A code repository manager."
homepage = "https://github.com/chasinglogic/projector"
categories = ["command-line-interface", "command-line-utilities", "filesystem"]
keywords = ["cli", "search", "files", "utility", "project"]
license = "GPL-3.0"
name = "projector"
readme = "README.md"
repository = "https://github.com/chasinglogic/projector"
version = "1.0.0"
edition = "2018"

[dependencies]
ansi_term = "*"
clap = { version = "*", features = ["derive"] }
dirs = "*"
regex = "*"
serde = { version = "*", features = ["derive"] }
serde_derive = "*"
serde_yaml = "*"
walkdir = "*"

[profile.release]
lto = true
