[package]
authors = ["Mathew Robinson <chasinglogic@gmail.com>"]
description = "Project management CLI"
homepage = "https://github.com/chasinglogic/projector"
categories = ["command-line-interface", "command-line-utilities", "filesystem"]
keywords = ["cli", "search", "files", "utility", "project"]
license = "GPL-3.0"
name = "projector"
readme = "README.md"
repository = "https://github.com/chasinglogic/projector"
version = "0.5.0"
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
clap = "2.33.0"
dirs = "2.0.2"
regex = "1.5.5"
serde = { version = "1.0.104", features = ["derive"] }
serde_derive = "1.0.104"
serde_yaml = "0.8.11"
walkdir = "2.3.1"

[profile.release]
lto = true
